### ISSUE TITLE
Edits not showing up in ARCHER

### ISSUE THREAD

**Issue by Hillarchives** [ewg118/eaditor#23]
I've added some subcomponents and information that is not showing up in Archer.

It is this record:

http://numismatics.org/archives/ark:/53695/nnan0075

http://admin.numismatics.org:8080/orbeon/eaditor/admin/edit/component/?guide=nnan0075&component=c_68ab98a442873ac67bcd1f42ea125202

**Comment by ewg118** [comment]
Tweaked URLs.
