### ISSUE TITLE
Flickr in DOAG not working

### ISSUE THREAD

**Issue by Hillarchives** [ewg118/eaditor#26]
Tried to add:

https://flic.kr/p/xqKXMg

to 

http://numismatics.org:8080/orbeon/eaditor/admin/edit/core/?guide=nnan0166

Error:

Error parsing flickr URI

**Comment by ewg118** [comment]
This should be fixed. I had to update the Flickr login to use https:// instead of http://. Please try again.

**Comment by Hillarchives** [comment]
Great, thanks.

David

David Hill
Francis D. Campbell Librarian
American Numismatic Society
75 Varick Street, 11th Floor
New York, NY  10013
Tel: (212) 571-4470, ext. 109
hill@numismatics.org

Join the American Numismatic Society and receive the award-winning quarterly ANS Magazine
