### ISSUE TITLE
Unwanted display text

### ISSUE THREAD

**Issue by Hillarchives** [ewg118/eaditor#28]
Somewhere along the way ARCHER started displaying "Other Descriptive Data" in component lists, e.g., here: 

http://numismatics.org/archives/ark:/53695/nnan0034

**Comment by ewg118** [comment]
Merged code from the master branch. fixed.

**Comment by Hillarchives** [comment]
Excellent. Thanks.

David

David Hill
Francis D. Campbell Librarian
American Numismatic Society
75 Varick Street, 11th Floor
New York, NY  10013
Tel: (212) 571-4470, ext. 109
hill@numismatics.org

Join the American Numismatic Society and receive the award-winning quarterly ANS Magazine
