### ISSUE TITLE
Path /eaditor/ not found.

### ISSUE THREAD

**Issue by podengo** [ewg118/eaditor#29]
Hi Ethan,

I have been following the eaditor wiki "Deployment" instructions, setting up Tomcat7, solr 4.10.4, existDB, orbeon, eaditor for last couple of days on a redhat 7 system.

Now I can browse my Tomcat localhost to see /solr, /exist, /orbeon pages that look good, but for /orbeon/eaditor and /orbeon/eaditor/admin the web page response just says "Orbeon Forms - Page Not found .. Sorry...". The orbeon log has these tail lines:
---
2016-02-17 13:32:26,880 INFO  lifecycle  - event: {"request": "86", "session": "9C7397BF09295DDC2A936B9A36149598", "source": "service", "message": "start: handle"}
2016-02-17 13:32:26,880 INFO  ProcessorService  - /eaditor/ - Received request
2016-02-17 13:32:26,886 INFO  PageFlowControllerProcessor  - not found {controller: "oxf:/page-flow.xml", method: "GET", path: "/eaditor/", resource: "/apps/eaditor/page-flow.xml"}
---
My eaditor last commit is 19e519 (Feb 10) , and under my eaditor git repo, file page-flow.xml has a notice saying Copyright 2007 Orbeon, Inc. 

I am a novice at Tomcat and Servlets, but I have double-checked various xxx.xml config files to make sure they comply with the Wiki's links's instructions. Can you advise any things to try?

Thank you!

**Comment by podengo** [comment]
Didn't mean to shout... something about how I copy/pasted in some text made for some HUGE font... I meant it all to be normal....

**Comment by ewg118** [comment]
The Orbeon pipelines are pretty particular about trailing slashes. Can you try /orbeon/eaditor/ and /orbeon/eaditor/admin/ ?

**Comment by podengo** [comment]
Thanks Ethan, for your quick response. I had tried the trailing slashes too, though I got the same results.
I had also edited an ...Catalina/localhost/orbeon.xml file to set a variable allowLinking to true, per the instructions found on Feb 17, 2016, at: https://github.com/ewg118/eaditor/wiki/Deploying-Orbeon

However, this morning I decided to try to remove the symlink and simply copy:

$ sudo cp -r /usr/local/projects/eaditor /var/lib/tomcat/webaps/orbeon/WEB-INF/resources/apps/eaditor

Then the EADitor pages came up immediately!
 
So this is also a proof that RHEL 7 supports EADitor, though the instructions about creating the symlink may need a footnoot for Redhat.

**Comment by ewg118** [comment]
Okay, are you running Tomcat 7 or 8? I have noticed symlinking changed in
Tomcat 8, but I haven't migrated any systems to it yet, so I'm not sure
what the workaround is.

**Comment by podengo** [comment]
Running Tomcat 7.0.54 on this machine.

**Comment by ewg118** [comment]
Okay. I will close for now. The symlink instructions have worked on Tomcat 6 and 7 in Ubuntu, so I am surprised that there is a difference between RHEL 7.
