### ISSUE TITLE
 Controlled access headings: can't see longer headings when searching vocabs

### ISSUE THREAD

**Issue by jenpalmentiero** [ewg118/eaditor#32]
When searching for controlled access headings, it is difficult to see if a given heading in the search list is the one you want.  It would be extremely helpful, especially for longer headings, if users could hover over the headings with their mouse to see the full form of the heading before selecting it (or otherwise make it easier for them to see entire headings in the list of suggested terms).

**Comment by ewg118** [comment]
This has been resolved. When clicking on an item in the select box for any of the controlled access heading types, the full label or definition (if there is a definition, e.g., from the Getty thesauri or Pleiades) will display underneath the select list. The user can click a link to spawn a new browser window to view the external page about the entity.
