### ISSUE TITLE
 Save function

### ISSUE THREAD

**Issue by jenpalmentiero** [ewg118/eaditor#34]
It would be helpful to have a way to save a guide as you are working on it. Right now you can only save once every required field is populated. So you can't save before moving from the EAD Header tab to the Archival Description tab (the message that all required fields must be filled in before saving can be confusing to new users at this stage).

**Comment by ewg118** [comment]
It is possible to move to other tabs before saving. The issue seems to be that a required field doesn't have a warning label, so it's difficult to figure out which element in the form that needs to be filled in hasn't been yet.

**Comment by jenpalmentiero** [comment]
I know I can move to another tab before saving. What I'm suggesting is the ability to click "Save" once the two fields in the EAD Header are filled-in before I move to the Archival Description Tab. Right now I can't do that.

**Comment by ewg118** [comment]
This can't be supported. The system doesn't accept documents that are invalid to the EAD 2002 XSD.

**Comment by jenpalmentiero** [comment]
OK. We'll include info about this in the instructions/training materials. If there are required fields that don't currently have the warning label, I assume that's an easy fix? Thanks!

**Comment by ewg118** [comment]
I'll have to track them down and try to make the warning message more visible.

**Comment by ewg118** [comment]
Hopefully, we have eliminated most of these outstanding issues. It will help to have documentation of which fields don't seem to save correctly.
