### ISSUE TITLE
Controlled access headings

### ISSUE THREAD

**Issue by jenpalmentiero** [ewg118/eaditor#35]
When I searched for a corporate name (“Hunter College”), only 10 results appeared—even though the system was telling me that it was displaying the first 100 of 71 results (???).  I saw a couple of headings with Hunter College subdivisions but not the basic heading for the college.  Also, I noticed that search results do not display in alphabetical order.  Hopefully this could be adjusted in the final version of the system!?

**Comment by ewg118** [comment]
Altered output so that it returns the exact count if below 100 and 'First 100 of > 100' results.

**Comment by jenpalmentiero** [comment]
Just tried the same search: "Hunter College" using VIAF for the lookup to create a Corporate Name controlled access heading. It says "Displaying 72 results" but I really only get 10 results and the basic heading for the college is not included in those 10.

**Comment by ewg118** [comment]
This is a VIAF bug. VIAF no longer returns more than 10 hits, of which Hunter College is not one. There is no way to control relevance of search. VIAF's web services are particularly poor in this regard.
