### ISSUE TITLE
Ability to Add paragraphs

### ISSUE THREAD

**Issue by senyzspalding** [ewg118/eaditor#38]
Have a request to add paragraphs like in a Word document, i.e., two returns. Instead of having to click up and through and out of the “Descriptive Identification Elements” for each new paragraph.

Perhaps a hot key will resolve this issue

**Comment by ewg118** [comment]
Can be implemented within the paragraph component. An XForms trigger to add paragraph to next XPath node

**Comment by ewg118** [comment]
Added New Paragraph button to insert a new paragraph directly below current one.
