### ISSUE TITLE
Add a warning/confirmation when deleting a field

### ISSUE THREAD

**Issue by jenpalmentiero** [ewg118/eaditor#40]
At the first training some people accidentally deleted a field (they meant to click the plus sign to add another sub-element, but clicked the X by accident. It was recommended that they get a warning message when they click the X that says something like, "Are you sure you want to delete this field. Any data you have entered will be lost." From the warning message they can click a "Delete" or "Cancel" button.

**Comment by ewg118** [comment]
Implement at higher level Component-level elements, like controlaccess and bioghist

**Comment by ewg118** [comment]
The dialog box to confirm deletion has been implemented for component level items in the archdesc. DACS-required elements cannot be deleted at this level (accessrestrict, userestrict, scopecontent, bioghist)
