### ISSUE TITLE
LCNAF

### ISSUE THREAD

**Issue by jenpalmentiero** [ewg118/eaditor#42]
Please provide Library of Congress Name Authority File as a lookup for Personal Names and Corporate Names for collection creators and controlled access headings.

**Comment by ewg118** [comment]
LCNAF lookups have been implemented for corpname and persname anywhere in the finding aid. The default response is 20 hits. I'm still looking to increase this to 100.

**Comment by ewg118** [comment]
This has been done. LCNAF is the primary response.
