### ISSUE TITLE
Change some includes for HTTPS to work correctly

### ISSUE THREAD

**Issue by senyzspalding** [ewg118/eaditor#44]
Change http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css to use the https version https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css.

Change http://maps.google.com/maps/api/js?v=3.2&amp;sensor=false to 
https://maps.google.com/maps/api/js?v=3.2&amp;sensor=false

Change http://openlayers.org/api/2.12/OpenLayers.js to {$include_path}ui/javascript/OpenLayers.js
(I do have a copy of OpenLayers.js on the server now in the includes folder)

**Comment by ewg118** [comment]
I'm going to put this on the back burner, as I might migrate from OpenLayers to Leaflet and drop the Google Maps API entirely.

**Comment by ewg118** [comment]
Done.
