### ISSUE TITLE
User local copy of OpenLayers.js

### ISSUE THREAD

**Issue by senyzspalding** [ewg118/eaditor#52]
Need to switch from
http://openlayers.org/api/2.12/OpenLayers.js
to
{$include_path}ui/javascript/OpenLayers.js

openlayers.org does not support https on there own server

Should be in these five files
ui/xslt/serializations/ead/html.xsl
ui/xslt/serializations/tei/html.xsl
ui/xslt/pages/maps_fullscreen.xsl
ui/xslt/pages/maps.xsl
xforms/tei.xhtml

**Comment by ewg118** [comment]
I am not sure why this is necessary

**Comment by senyzspalding** [comment]
Most if not all browsers won't load unecypted data from includes when a site is doing https.
https://www.empireadc.org/maps

The EAD site is moving to https as part of ESLN group being committed to the https://libraryfreedomproject.org/ for the services that it provides.

**Comment by ewg118** [comment]
Done.
