### ISSUE TITLE
Repository element in template

### ISSUE THREAD

**Issue by jenpalmentiero** [ewg118/eaditor#53]
Please include the Repository element in the template. Also include these sub-elements: corpname, subarea, address, extref

**Comment by ewg118** [comment]
Okay, the individual template files have not yet been updated on the server, but the underlying code for the repository element now allows the entry of the corpname (which is a required element by default), subarea, address, and extref

**Comment by ewg118** [comment]
I should note that I switched this to an extptr in EAD. The extptr is just a simple URL input. extref requires a URL and a bit of human readable text (like if you were going to insert a link directly into a paragraph). We don't really need that in this context.
