### ISSUE TITLE
Container element, Type attribute drop-down list

### ISSUE THREAD

**Issue by jenpalmentiero** [ewg118/eaditor#57]
Please provide a list of standard container types to the Type attribute drop-down list for the Container element.

**Comment by ewg118** [comment]
The container drop down had been placed inside the attribute pop-up menu, which is opened with the @ symbol. This wasn't readily intuitive, especially for an attribute that will be heavily used. I moved the drop down menu directly in the same line with the container input. Let me know what you think.
