### ISSUE TITLE
Reorder error

### ISSUE THREAD

**Issue by Hillarchives** [ewg118/eaditor#61]
For this record http://numismatics.org:8080/orbeon/eaditor/admin/edit/core/?guide=nnan0123

Selected "reorder" under actions. Got this error:

Orbeon Forms - An Error has Occurred

An error has occurred in Orbeon Forms. You may want to try one of the following:

If this error occurred when you followed a link, press your browser's Back button.
If the above does not work, try reloading the page:
With Firefox: hold down the shift key and click the Reload button in your browser toolbar.
With Safari and Chrome: click the Reload button in your browser toolbar.
With Internet Explorer: hold down the control key and click the Reload button in your browser toolbar.
Return home.
Orbeon Forms 4.5.0.201404080036 CE

**Comment by ewg118** [comment]
I have fixed this, but it's in the master Github branch for EADitor, and the change hasn't been implemented yet in Archer. I plan to sync Archer up to main EADitor changes soon.
