### ISSUE TITLE
Facet search box doesn't work

### ISSUE THREAD

**Issue by jenpalmentiero** [ewg118/eaditor#64]
Each of the facets (except date) has its own search box, but they don't work. Do we need them or is the Advanced Search page a better place to search on an individual facet?

**Comment by ewg118** [comment]
The facet search box is case-sensitive. I'm not sure how to change this. It's inherent to the code of the multiselect Javascript plugin.

**Comment by ewg118** [comment]
I located an updated version of this plugin (was using one that was 2-3 years old) which now supports case insensitive searching. You may need to clear your cache for your browser to download the updated javascript from the server.
