### ISSUE TITLE
Add Header and Footer

### ISSUE THREAD

**Issue by senyzspalding** [ewg118/eaditor#65]
Can you do an include of these two files for a header and footer?  I am thinking if you can do some type of include statement these files can be modified with out having to do anything to Eaditor

Header
http://www.empireadc.org/sites/www.empireadc.org/files/ead_header_include.html

Footer
http://www.empireadc.org/sites/www.empireadc.org/files/ead_footer_include.html

**Comment by ewg118** [comment]
Okay, but it will have to wait until we create the fork as the XSLT templates for the header and footer (in templates.xsl) will need to call these via iframes or something.

**Comment by ewg118** [comment]
This has been applied to fork
